### ISSUE TITLE
Exception upon startup

### ISSUE THREAD

**Issue by Ghastly181** [CaptainHorse/MAS-Additions#19]
I transferred both the repository and binary for windows into my submods folder but now when I start up MAS I get this exception for invalid syntax.

> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 1, in script
>     init 5 python:
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 22, in <module>
>     unlocked=True
>   File "game/definitions.rpy", line 717, in __init__
> SyntaxError: invalid syntax (<none>, line 1)
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 1, in script
>     init 5 python:
>   File "C:\Users\Sahil\AppData\Roaming\DokiDokiModManager\GameData\installs\backup-mas\install\renpy\ast.py", line 814, in execute
>     renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
>   File "C:\Users\Sahil\AppData\Roaming\DokiDokiModManager\GameData\installs\backup-mas\install\renpy\python.py", line 1719, in py_exec_bytecode
>     exec bytecode in globals, locals
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 22, in <module>
>     unlocked=True
>   File "game/definitions.rpy", line 717, in __init__
>   File "C:\Users\Sahil\AppData\Roaming\DokiDokiModManager\GameData\installs\backup-mas\install\renpy\python.py", line 584, in py_compile
>     raise e
> SyntaxError: invalid syntax (<none>, line 1)
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187
> Monika After Story 0.12.2

**Comment by DatCaptainHorse** [comment]
Currently going to remove my wisdom teeth, I'll see to a fix after that. I probably did an oopsie reverting merge changes.

**Comment by DatCaptainHorse** [comment]
Could you re-download the repository (https://github.com/CaptainHorse/MAS-Additions/archive/refs/heads/master.zip) and overwrite the old files?

Just in case remove these files as well:
* FaceDetectionAndRecognition.rpyc
* FaceDetectionAndRecognition_Topics.rpyc
* MonikaAfterStoryModule.rpyc
* MIDISupport.rpyc

Mind the .rpyc extension! Don't remove .rpy ones!

**Comment by Ghastly181** [comment]
I did as you said and made sure to remove the .rpyc files but still got the same traceback.

**Comment by DatCaptainHorse** [comment]
Not sure why your instance complains as there are no comma issues.

I pushed a change that moves the "unlocked=True" up by 1 so it looks identical to the other addEvent, just re-download the repo using same link and overwrite old files.

**Comment by Ghastly181** [comment]
I replaced the files with the updated repo but its still having trouble with line 22 for some strange reason

> [code]
> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 1, in script
>     init 5 python:
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 22, in <module>
>     aff_range=(mas_aff.NORMAL, None)
>   File "game/definitions.rpy", line 717, in __init__
> SyntaxError: invalid syntax (<none>, line 1)
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 1, in script
>     init 5 python:
>   File "C:\Users\Sahil\AppData\Roaming\DokiDokiModManager\GameData\installs\backup-mas\install\renpy\ast.py", line 814, in execute
>     renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
>   File "C:\Users\Sahil\AppData\Roaming\DokiDokiModManager\GameData\installs\backup-mas\install\renpy\python.py", line 1719, in py_exec_bytecode
>     exec bytecode in globals, locals
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 22, in <module>
>     aff_range=(mas_aff.NORMAL, None)
>   File "game/definitions.rpy", line 717, in __init__
>   File "C:\Users\Sahil\AppData\Roaming\DokiDokiModManager\GameData\installs\backup-mas\install\renpy\python.py", line 584, in py_compile
>     raise e
> SyntaxError: invalid syntax (<none>, line 1)
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187
> Monika After Story 0.12.2
> [/code]

I'm starting to think that my instance may just be a lost cause for whatever reason

**Comment by Ghastly181** [comment]
i got a fresh copy of the definitions.rpy file from the official mas repo and it gives an extra line of traceback text when i run with the submod

> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 1, in script
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 22, in <module>
>   File "game/definitions.rpy", line 717, in __init__
>     Event._conditional_cache[self.conditional] = renpy.python.py_compile(self.conditional, "eval")
> SyntaxError: invalid syntax (<none>, line 1)
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 1, in script
>   File "C:\Users\Sahil\AppData\Roaming\DokiDokiModManager\GameData\installs\backup-mas\install\renpy\ast.py", line 814, in execute
>     renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
>   File "C:\Users\Sahil\AppData\Roaming\DokiDokiModManager\GameData\installs\backup-mas\install\renpy\python.py", line 1719, in py_exec_bytecode
>     exec bytecode in globals, locals
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 22, in <module>
>   File "game/definitions.rpy", line 717, in __init__
>>      Event._conditional_cache[self.conditional] = renpy.python.py_compile(self.conditional, "eval")
>   File "C:\Users\Sahil\AppData\Roaming\DokiDokiModManager\GameData\installs\backup-mas\install\renpy\python.py", line 584, in py_compile
>     raise e
> SyntaxError: invalid syntax (<none>, line 1)
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187
> Monika After Story 0.12.2

maybe it could have something to do with the conditionals?

**Comment by DatCaptainHorse** [comment]
> maybe it could have something to do with the conditionals?

Nope. I think your installation is borked somehow, it keeps pointing to line 22 no matter what is there. I'm not sure how DokiDokiModManager works but it seems to cause very long paths (like `C:\Users\Sahil\AppData\Roaming\DokiDokiModManager\GameData\installs\backup-mas\install\renpy ` ), could be hitting Windows' age-old path length limit?

**Comment by Ghastly181** [comment]
I transferred my MAS installation out of DDMM and onto my desktop so at this point there shouldn't be any path length limits. 
Yet I'm still getting the traceback

> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 1, in script
>     init 5 python:
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 22, in <module>
>     aff_range=(mas_aff.NORMAL, None)
>   File "game/definitions.rpy", line 717, in __init__
>     Event._conditional_cache[self.conditional] = renpy.python.py_compile(self.conditional, "eval")
> SyntaxError: invalid syntax (<none>, line 1)
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 1, in script
>     init 5 python:
>   File "C:\Users\Sahil\Desktop\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
>     renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
>   File "C:\Users\Sahil\Desktop\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
>     exec bytecode in globals, locals
>   File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 22, in <module>
>     aff_range=(mas_aff.NORMAL, None)
>   File "game/definitions.rpy", line 717, in __init__
>     Event._conditional_cache[self.conditional] = renpy.python.py_compile(self.conditional, "eval")
>   File "C:\Users\Sahil\Desktop\DDLC-1.1.1-pc\renpy\python.py", line 584, in py_compile
>     raise e
> SyntaxError: invalid syntax (<none>, line 1)
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187
> Monika After Story 0.12.2

Edit: Also did another fresh install of mas afterstory without all my submods and whatnot that also gets the same exception when run with this submod

**Comment by Ghastly181** [comment]
did a test where i got rid of the conditional line from the face detection override event and MAS booted up perfectly fine with teh submod working. So i think it might have something to do with the conditional or maybe my installs are just completely borked in a unique way.

**Comment by DatCaptainHorse** [comment]
I simplified the conditionals to only 2 checks: `if FDAR.canRecognize() and not renpy.seen_label('submods_dathorse_facedetection_firsttime')`

Not sure why conditionals have issues for you as no-one else has had the same issue.
I'll re-open this incase someone does have the same issue, they'll be able to find this and voice their thoughts.

**Comment by MiguelFitz** [comment]
My Lords, i came here for your help and Knowledge... pleeaaseeee T.T

just tell me what to do and where, i didnt full understand it 

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 21, in <module>
    aff_range=(mas_aff.NORMAL, None)
  File "game/definitions.rpy", line 717, in __init__
SyntaxError: unexpected EOF while parsing (<none>, line 1)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "lib/windows-i686/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpyc", line 1, in script
  File "C:\Users\migue\OneDrive\Documentos\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\migue\OneDrive\Documentos\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/Submods/MAS Additions/FaceDetectionAndRecognition_Topics.rpy", line 21, in <module>
    aff_range=(mas_aff.NORMAL, None)
  File "game/definitions.rpy", line 717, in __init__
  File "C:\Users\migue\OneDrive\Documentos\DDLC-1.1.1-pc\renpy\python.py", line 584, in py_compile
    raise e
SyntaxError: unexpected EOF while parsing (<none>, line 1)

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.2
[/code]

**Comment by DatCaptainHorse** [comment]
I'm going to ask someone bit more experienced to help with this issue, not sure why Ren'Py is throwing a fit. I'll update once this comment (or make a new one) once I find something.

**Comment by MiguelFitz** [comment]
i try the old version and start up good, the problem now is that it cant recognice my camara, but i guess is a step in the rigth direction, i dont know is that is useful information for you, but its all i can do sadly....

**Comment by DatCaptainHorse** [comment]
> i try the old version and start up good, the problem now is that it cant recognice my camara, but i guess is a step in the rigth direction, i dont know is that is useful information for you, but its all i can do sadly....

Thanks for taking the time to try that, I'm guessing the current file is somehow corrupted. Once I have time I'll replace it with old file and remake the changes.

**Comment by MiguelFitz** [comment]
dont worry, ill try to help in all that i can, let me know if theres someway to help...i mean i dont know that much of program yet,but ill try

**Comment by DatCaptainHorse** [comment]
Okay I removed the file from repo and re-added it, hopefully that's enough for Git to understand so corruption leaves.

**Comment by DatCaptainHorse** [comment]
Would someone be willing to help test things out faster through Discord?

**Comment by MiguelFitz** [comment]
On Saturday it a good day? It the only day I could help for a bit

Get Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DatCaptainHorse** [comment]
> On Saturday it a good day? It the only day I could help for a bit Get Outlook para Android<https://aka.ms/AAb9ysg>

Depends on time (and timezone), but it could work.

**Comment by MiguelFitz** [comment]
I'm in standard central zone (GTM-6)
So let me know if it good,when you are free and we can give it a shot
Get Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DatCaptainHorse** [comment]
Whew 9 hours of timezone difference. I'd be free for around 11am - 3pm your time (possibly longer if I don't get tired early).

**Comment by MiguelFitz** [comment]
I think I'll be free at that time,let me know if you want me to help or if you find a better option ,I'll be waiting

Get Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DatCaptainHorse** [comment]
> I think I'll be free at that time,let me know if you want me to help or if you find a better option ,I'll be waiting

I'd appreciate the help, you can contact me through Discord (DatHorse#9516). If your schedule changes send me a message and well find some other time.

**Comment by MiguelFitz** [comment]
welp, as you say my schedule just change a little bit, i have exam at 2 pm, so im gonna try to finish in time (its in group so i dont think it gonna take to much), also i just send you invitation in discord

**Comment by DatCaptainHorse** [comment]
Closing, can't remember exactly what the outcome was, but I'm assuming it's somewhat fixed as this is an older issue.
